---
- name: Check if a new Podman image is available and publish to MQTT
  hosts: all
  become: true
  vars:
    docker_image_name: "{{ podman_image_name }}"
    mqtt_host: "{{ mqtt_host }}" 
    mqtt_port: "{{ mqtt_port }}"            
    mqtt_topic: "{{  mqtt_topic }}" 
  tasks:
    - name: Get local Podman image information
      containers.podman.podman_image_info:
        name: "{{ podman_image_name }}"
      register: local_image_info

    - name: Pull the latest Podman image
      containers.podman.podman_image:
        name: "{{ podman_image_name }}"
        state: present
      register: pulled_image_info

    - name: Check if a new image was pulled
      set_fact:
        new_image_available: "{{ pulled_image_info.changed }}"

    - name: Publish MQTT message if new image is available
      mqtt:
        server: "{{ mqtt_host }}"
        port: "{{ mqtt_port }}"
        topic: "{{ mqtt_topic }}"
        username: "{{ mqtt_username }}"
        password: "{{ mqtt_password }}"
        payload: "New Podman image for {{ podman_image_name }} is available and pulled."
      when: new_image_available

    - name: Publish MQTT message if no new image is available
      mqtt:
        server: "{{ mqtt_host }}"
        port: "{{ mqtt_port }}"
        topic: "{{ mqtt_topic }}"
        username: "{{ mqtt_username }}"
        password: "{{ mqtt_password }}"
        payload: "No new Podman image for {{ podman_image_name }}."
      when: not new_image_available
