---
- hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Podman
      apt:
        name: podman
        state: present

    - name: Enable and start podman socket
      systemd:
        name: podman.socket
        enabled: yes
        state: started

    # Ajoute ici tes tasks pour config, déploiements, etc.
