---
- name: Restart service
  hosts: all
  become: true
  vars:
    service: "{{ service }}"
  
  tasks:
  - name: Restart service "{{ service }}", in all cases
    ansible.builtin.service:
      name: "{{ service }}"
      state: restarted
