---
- name: Move VM in Proxmox cluster
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Move VM from one node to another
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        name: 108
        node: pve1
        migrate: true
      register: result

    - name: Print result of the migration
      debug:
        var: result
