---
- name: Update APT caches on all servers
  hosts: all
  tasks:
  - name: Run apt-get update
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: Upgrade all installed packages
    apt:
      upgrade: dist
      force_apt_get: yes
      autoremove: yes
